#!/bin/sh

get_clean_message() {
  egrep -o '^[^#].*' "$1"
}

[ -z "$(get_clean_message "$1")" ] && {
  echo >&2 Commit message cannot be empty.
  exit 1
}

get_clean_message "$1" | egrep -qi '\b[A-Z]{3,}-[1-9][0-9]*\b' || {
  echo >&2 Commit message requires JIRA code.
  exit 1
}

#testing
#echo "ok"
#exit 1
